---
apiVersion: v1
kind: Namespace
metadata:
  name: bow-api
---
apiVersion: v1
data:
  MONGO_DB_HOSTNAME: mongo
  MONGODBDATABASE: boozeonwheel
  SERVERHOST: 0.0.0.0
  FILE_PATH: /data/files
  AWS_ENDPOINT_URL: https://s3.ap-south-1.amazonaws.com
  AWS_ACCESS_KEY: AKIAI3YUCOGLGYGO4R7A
  AWS_SECRET_KEY: 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
  AWS_BUCKET_NAME: boozeonwheel.com
kind: ConfigMap
metadata:
  name: bow-api-config
  namespace: bow-api
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bow-api-app
  namespace: bow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bow-api-app
  template:
    metadata:
      labels:
        app: bow-api-app
    spec:
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim
      containers:
        -
          env:
            -
              name: MONGODBHOST
              valueFrom:
                configMapKeyRef:
                  key: MONGO_DB_HOSTNAME
                  name: bow-api-config
            -
              name: MONGODBDATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGODBDATABASE
                  name: bow-api-config
            -
              name: FILEPATH
              valueFrom:
                configMapKeyRef:
                  key: FILE_PATH
                  name: bow-api-config
            -
              name: AWSENDPOINTURL
              valueFrom:
                configMapKeyRef:
                  key: AWS_ENDPOINT_URL
                  name: bow-api-config

            -
              name: AWSACCESSKEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY
                  name: bow-api-config
            -
              name: AWSSECRETKEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_KEY
                  name: bow-api-config

            -
              name: AWSBUCKETNAME
              valueFrom:
                configMapKeyRef:
                  key: AWS_BUCKET_NAME
                  name: bow-api-config

          image: "lalit1980/bow-product-svc:tagVersion"
          volumeMounts:
          - mountPath: "/data/files"
            name: mypd
          imagePullPolicy: Always
          name: bow-api-app
          ports:
            -
              containerPort: 9010
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bow-api-service
  namespace: bow-api
spec:
  clusterIP: None
  ports:
    - port: 9010 # custom value.
  selector:
    app: bow-api-app

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: api
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: bow-api
spec:
  commonName: boozeonwheels.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bow-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.bow.boozeonwheels.com
    secretName: selfsigned-cert-tls
  rules:
  - host: api.bow.boozeonwheels.com
    http:
      paths:
      - path: /
        backend:
          serviceName: bow-api-service
          servicePort: 9010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: bow
        image: lalit1980/bow-product-svc:tagVersion
        ports:
        - containerPort: 80
---
