apiVersion: v1
kind: Namespace
metadata:
  name: bow

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: bow
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: bow
spec:
  commonName: boozeonwheels.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bow-ingress
  namespace: bow
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - boozeonwheels.com
    secretName: selfsigned-cert-tls
  rules:
  - host: boozeonwheels.com
    http:
      paths:
      - path: /
        backend:
          serviceName: bow-svc
          servicePort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bow
  namespace: bow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bow
  template:
    metadata:
      labels:
        app: bow
    spec:
      containers:
      - name: bow
        image: lalit1980/bow-ui-react:tagVersion
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: bow-svc
  namespace: bow
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: bow
