# Spring boot settings
spring:
  profiles: dev
  application:
    name: bow-product-svc
  servlet:
    multipart:
      maxRequestSize: 70000000
      maxFileSize: 70000000
  pid:
    file: build/bow-product-svc.pid

  jmx:
    enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: boozeonwheel
      
# --------------------------------------------------------------------------------------------------
mongo:
  min-connections: 2
  max-connections: 5
  connect-timeout-ms: 5000
  socket-timeout-ms: 5000

# --------------------------------------------------------------------------------------------------

logging:
  config: classpath:logback.xml

# --------------------------------------------------------------------------------------------------

# The embedded server settings
server:
  address: localhost
  port: 9010

# --------------------------------------------------------------------------------------------------

# Customise active actuator endpoints
endpoints:
  configprops:
    enabled: false
  info:
    enabled: false
  shutdown:
    enabled: false

# --------------------------------------------------------------------------------------------------

# Scheduler configuration
scheduler:
  auto-start: true
  startup-delay-seconds: 5
  cron-exp-export: "0/15 * * * * ?"
  cron-exp-archiving: "0/30 * * * * ?"

# --------------------------------------------------------------------------------------------------
files:
  folder: /var/bow/filestore
  max: 10000
amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIAQ2GFWIPHLQ2CPWI4
  secretKey: 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
  bucketName: boozeonwheel.com